name: story_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  get: ^4.7.2
  http: ^1.4.0
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.12.2
  google_maps_flutter_web: ^0.5.12
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
